namespace bretts_services.Controllers;

/// <summary>
/// AI Related endpoints for interacting with LMStudio's configured language model.  These endpoints call llmster which is the headless version of LMStudio.  Chatting with the LLM is done through these endpoints.
/// </summary>
[Authorize(Roles = "Admin")]
[ApiController]
[Route("[controller]")]
public class ChatController : ControllerBase
{
    private readonly IChatService _chatService;

    /// <summary>
    /// Initializes a new instance of the <see cref="ChatController"/> class.
    /// </summary>
    /// <param name="chatService">
    /// The service used to send prompts to the configured language model.
    /// </param>
    public ChatController(IChatService chatService)
    {
        _chatService = chatService;
    }

    /// <summary>
    /// Sends a prompt to the configured language model.  The response is streamed back to the client as it is generated.
    /// </summary>
    /// <param name="prompt">
    /// The prompt to send to the language model.
    /// </param>
    /// <returns>
    /// The response generated by the language model.
    /// </returns>
    /// <response code="200">
    /// Returns the response generated by the language model.
    /// </response>
    /// <response code="400">
    /// The prompt was empty or contained only whitespace.
    /// </response>
    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Chat([FromBody] string prompt)
    {
        if (string.IsNullOrWhiteSpace(prompt))
        {
            return BadRequest("The prompt string was empty.");
        }

        HttpContext.Features
        .Get<Microsoft.AspNetCore.Http.Features.IHttpResponseBodyFeature>()?
        .DisableBuffering();

        Response.ContentType = "text/plain; charset=utf-8";

        await foreach (var chunk in _chatService.ChatAsync(prompt))
        {
            await Response.WriteAsync(chunk);
            await Response.Body.FlushAsync();
        }

        return new EmptyResult();
    }

    /// <summary>
    /// Returns a string that is the name of the currently loaded language model in LMStudio.
    /// </summary>
    /// <returns>
    /// The string name of the currently loaded language model in LMStudio (llmster).
    /// </returns>
    /// <response code="200">
    /// A model was found to return.
    /// </response>
    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> GetLoadedModel()
    {
        string loadedModel = await _chatService.GetLoadedModelAsync();
        return Ok(loadedModel);
    }
}