namespace bretts_services.Controllers;

/// <summary>
/// Provides endpoints for interacting with LMStudio's configured language model.
/// </summary>
[Authorize(Roles = "Admin")]
[ApiController]
[Route("[controller]")]
public class ChatController : ControllerBase
{
    private readonly IChatService _chatService;

    /// <summary>
    /// Initializes a new instance of the <see cref="ChatController"/> class.
    /// </summary>
    /// <param name="chatService">
    /// The service used to send prompts to the configured language model.
    /// </param>
    public ChatController(IChatService chatService)
    {
        _chatService = chatService;
    }

    /// <summary>
    /// Sends a prompt to the configured language model.
    /// </summary>
    /// <param name="prompt">
    /// The prompt to send to the language model.
    /// </param>
    /// <returns>
    /// The response generated by the language model.
    /// </returns>
    /// <response code="200">
    /// Returns the response generated by the language model.
    /// </response>
    /// <response code="400">
    /// The prompt was empty or contained only whitespace.
    /// </response>
    /// <response code="401">
    /// The caller is not authenticated.
    /// </response>
    /// <response code="403">
    /// The caller is not authorized as an Admin.
    /// </response>
    [HttpPost]
    public async Task<IActionResult> Chat([FromBody] string prompt)
    {
        if (string.IsNullOrWhiteSpace(prompt))
        {
            return BadRequest("The prompt string was empty.");
        }
        
        return Ok(await _chatService.ChatAsync(prompt));
    }
}