namespace bretts_services.Controllers;

/// <summary>
/// Provides streaming chat and model-management endpoints backed by LM Studio's headless server, llmster.
/// </summary>
[Authorize(Roles = "Admin")]
[ApiController]
[Route("[controller]")]
public class ChatController : ControllerBase
{
    private readonly IChatService _chatService;

    /// <summary>
    /// Initializes a new instance of the <see cref="ChatController"/> class.
    /// </summary>
    /// <param name="chatService">
    /// The service used to send prompts to the configured language model.
    /// </param>
    public ChatController(IChatService chatService)
    {
        _chatService = chatService;
    }

    /// <summary>
    /// Sends a prompt to the current language model and streams its response.
    /// </summary>
    /// <param name="prompt">
    /// The prompt to send to the language model.
    /// </param>
    /// <returns>
    /// A plain-text response streamed as it is generated.
    /// </returns>
    /// <response code="200">
    /// Returns the response generated by the language model.
    /// </response>
    /// <response code="400">
    /// The prompt was empty or contained only whitespace.
    /// </response>
    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Chat([FromBody] string prompt)
    {
        if (string.IsNullOrWhiteSpace(prompt))
        {
            return BadRequest("The prompt string was empty.");
        }

        HttpContext.Features
        .Get<Microsoft.AspNetCore.Http.Features.IHttpResponseBodyFeature>()?
        .DisableBuffering();

        Response.ContentType = "text/plain; charset=utf-8";

        await foreach (var chunk in _chatService.ChatAsync(prompt))
        {
            await Response.WriteAsync(chunk);
            await Response.Body.FlushAsync();
        }

        return new EmptyResult();
    }

    /// <summary>
    /// Returns the model key of the current language model.
    /// </summary>
    /// <returns>
    /// The model key that identifies the current language model.
    /// </returns>
    /// <response code="200">
    /// The current language model was found and its model key is returned.
    /// </response>
    /// <response code="500">
    /// No language model is loaded or LM Studio (llmstr) could not return its model list.
    /// </response>
    [AllowAnonymous]
    [HttpGet]
    [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetLoadedModel()
    {
        string loadedModel = await _chatService.GetLoadedModelAsync();
        return Ok(loadedModel);
    }

    /// <summary>
    /// Returns the model keys for language models available in LM Studio (llmstr).
    /// </summary>
    /// <returns>
    /// The model keys that can be passed to <see cref="ChangeLoadedModel"/>.
    /// </returns>
    /// <remarks>
    /// Embedding models are not included.
    /// </remarks>
    /// <response code="200">
    /// The available language models were returned.
    /// </response>
    /// <response code="500">
    /// LM Studio (llmstr) could not return its model list.
    /// </response>
    [AllowAnonymous]
    [HttpGet("availablemodels")]
    [ProducesResponseType(typeof(IReadOnlyList<string>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAvailableModels()
    {
        var availableModels = await _chatService.GetAvailableModelsAsync();
        return Ok(availableModels);
    }

    /// <summary>
    /// Makes the requested language model the current model.
    /// </summary>
    /// <param name="model">
    /// The LM Studio (llmstr) model key to load, sent as a JSON string. Use a key returned by
    /// <see cref="GetAvailableModels"/>.
    /// </param>
    /// <returns>
    /// The model key of the loaded model.
    /// </returns>
    /// <remarks>
    /// The model key is validated before any model is unloaded. If the requested model is
    /// already current, no model change is made. If another model is current, that instance is
    /// unloaded before the requested model is loaded. If no model is currently loaded, the
    /// requested model is loaded directly.
    /// </remarks>
    /// <response code="200">
    /// The requested model is current and its model key is returned.
    /// </response>
    /// <response code="400">
    /// The model key was empty or contained only whitespace.
    /// </response>
    /// <response code="404">
    /// The requested language model is not available in LM Studio (llmstr).
    /// </response>
    /// <response code="500">
    /// LM Studio (llmstr) could not unload the current model or load the requested model.
    /// </response>
    [AllowAnonymous]
    [HttpPut("loadedmodel")]
    [Consumes("application/json")]
    [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> ChangeLoadedModel([FromBody] string model)
    {
        if (string.IsNullOrWhiteSpace(model))
        {
            return BadRequest("The model string was empty.");
        }

        var loadedModel = await _chatService.ChangeLoadedModelAsync(model);

        if (loadedModel == null)
        {
            return NotFound();
        }

        return Ok(loadedModel);
    }
}
