using bretts_services.Models.Entities;

namespace bretts_services.Controllers;

/// <summary>
/// Exposes administrative diagnostics used to demonstrate logging, error handling, and host shutdown.
/// </summary>
[Authorize(Roles = "Admin")]
[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{
    private readonly ILogger<TestController> _logger;
    private readonly IHostApplicationLifetime _hostApplicationLifetime;
    private readonly BrettsAppContext _brettsAppContext;

    /// <summary>
    /// Initializes a new instance of the <see cref="TestController"/> class.
    /// </summary>
    /// <param name="logger">The controller logger.</param>
    /// <param name="hostApplicationLifetime">The application lifetime used to stop the host.</param>
    /// <param name="brettsAppContext">The database context used by diagnostic actions.</param>
    public TestController(ILogger<TestController> logger, IHostApplicationLifetime hostApplicationLifetime, BrettsAppContext brettsAppContext)
    {
        _logger = logger;
        _hostApplicationLifetime = hostApplicationLifetime;
        _brettsAppContext = brettsAppContext;
    }

    /// <summary>
    /// Requests a graceful shutdown of the API host.
    /// </summary>
    /// <remarks>
    /// This diagnostic action stops the running API process. An authenticated user with the
    /// Admin role is required.
    /// </remarks>
    /// <returns>An empty success response when the shutdown request is accepted.</returns>
    /// <response code="200">The host accepted the shutdown request.</response>
    /// <response code="401">The request does not contain a valid JWT access token.</response>
    /// <response code="403">The authenticated user does not have the Admin role.</response>
    [HttpDelete("shutdown")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public IActionResult Shutdown()
    {
        _logger.LogCritical("Shutting down the server.");
        
        _hostApplicationLifetime.StopApplication();

        return Ok();
    }

    /// <summary>
    /// Throws a deliberate exception to exercise global error handling.
    /// </summary>
    /// <remarks>
    /// This diagnostic action always throws an <see cref="ArgumentException"/>. The global
    /// exception handler converts it to a standard problem-details response.
    /// </remarks>
    /// <returns>A problem-details response generated by the global exception handler.</returns>
    /// <response code="401">The request does not contain a valid JWT access token.</response>
    /// <response code="403">The authenticated user does not have the Admin role.</response>
    /// <response code="500">Returns problem details for the deliberate exception.</response>
    [HttpGet("throwerror")]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public IActionResult ThrowError()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(null, "Hello there yall!");

        return Ok();
    }

    /// <summary>
    /// Writes a structured log entry containing a sample user.
    /// </summary>
    /// <remarks>
    /// Loads the first available user and writes it as a structured Serilog property. An
    /// authenticated user with the Admin role is required.
    /// </remarks>
    /// <returns>An empty success response after the log entry is written.</returns>
    /// <response code="200">The structured log entry was written.</response>
    /// <response code="401">The request does not contain a valid JWT access token.</response>
    /// <response code="403">The authenticated user does not have the Admin role.</response>
    /// <response code="500">An unexpected server or database error occurred.</response>
    [HttpGet("structuredlogentry")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> StructuredLogEntry()
    {
        var user = await _brettsAppContext.Users.FirstOrDefaultAsync();

        _logger.LogInformation("You are a superstar! {@superstar}", user);

        return Ok();
    }
}
